name: docker-push
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Grab MetaData
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: ${{ secrets.DOCKER_USERNAME }}/wasky-ceg3120
            tags: |
              type=raw,value=latest
              type=semver,pattern={{major}}
              type=semver,pattern={{major}}.{{minor}}


      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./Project4       # Changes the working directory to project 4
          file: ./Project4/Dockerfile
          #platforms: linux/amd64,linux/arm64    # Cross Platform
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
